apiVersion: v1
kind: PersistentVolume
metadata:
    name: mysql-pv2
spec:
    capacity:
        storage: 10Gi
    accessModes:
        - ReadWriteOnce
        - ReadOnlyMany
    persistentVolumeReclaimPolicy: Retain
    gcePersistentDisk:
        pdName: mysql-2
        fsType: ext4
    storageClassName: standard
